[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hotpotqa-group-d"
version = "0.1.0"
dependencies = ["mistralai", "python-dotenv"]

[tool.setuptools.packages.find]
where = ["src"]
