[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hpqaGroupD"
version = "0.1.0"
dependencies = ["mistralai"]

[tool.setuptools.packages.find]
where = ["src"]
